# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 22:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('watchout', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_len', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_id', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.TextField()),
                ('check_in', models.DateTimeField(default=django.utils.timezone.now)),
                ('log_user', models.DateTimeField(default=django.utils.timezone.now)),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watchout.Company')),
            ],
        ),
        migrations.RemoveField(
            model_name='watchout',
            name='employee',
        ),
        migrations.DeleteModel(
            name='Watchout',
        ),
        migrations.AddField(
            model_name='admin',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watchout.Employees'),
        ),
    ]
