# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchout', '0003_auto_20160425_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='emp_id',
            field=models.CharField(max_length=300),
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
