# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchout', '0004_auto_20160427_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='password',
            field=models.CharField(default=1234, max_length=10),
            preserve_default=False,
        ),
    ]
